### ISSUE TITLE
xgen/xgen/cg.cpp: 2 * dead pointer usage

### ISSUE THREAD

**Issue by dcb314** [stevenknown/xgen#1]
[xgen/xgen/cg.cpp:3403]: (error) Dead pointer usage. Pointer 'opndnum' is dead if it has been assigned '&o1' at line 3401.
[xgen/xgen/cg.cpp:3404]: (error) Dead pointer usage. Pointer 'resnum' is dead if it has been assigned '&o1' at line 3402.

**Comment by stevenknown** [comment]
Yes, it is tricky usage that assume o1's memory location on stack is not overlapped to 'the_tn'. I'm going to fix it up.
